### ISSUE TITLE
Issue building the MudBlazor Template

### ISSUE THREAD

**Issue by Dukenware** [ubhaya/CleanArchitecture.Blazored#37] opened 2024-02-20 20:14 UTC
Hello,
I'm having an issue running the template (both versions, but my focus is on the MudBlazor version at the moment).
After creating the template (name MudBlazorCleanTest), first I run into this issue:

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0576	Namespace '<global namespace>' contains a definition conflicting with alias 'System'	WebUi.Client	C:\Users\Dukenware\source\repos\MudBlazorCleanTest\src\WebUi\WebUi.Client\ApiClients.g.cs	455	Active	

it's probably caused by the file even existing in the first place, so I delete the ApiClients.g.cs from the project. That helps, but then I get into another issue:

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		Project "C:\Users\Dukenware\source\BuildSettings\MudBlazorCleanTest.props" was not imported by "C:\Users\Dukenware\source\repos\MudBlazorCleanTest\src\WebUi\WebUi\WebUi.csproj" at (3,3), due to the file not existing.	WebUi	C:\Users\Dukenware\source\BuildSettings\MudBlazorCleanTest.props	3		

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		Project "C:\Users\Dukenware\source\BuildSettings\MudBlazorCleanTest.targets" was not imported by "C:\Users\Dukenware\source\repos\MudBlazorCleanTest\src\WebUi\WebUi\WebUi.csproj" at (49,3), due to the file not existing.	WebUi	C:\Users\Dukenware\source\BuildSettings\MudBlazorCleanTest.targets	49		

I can confirm the files are indeed missing.

I followed the instructions from the tutorial, any help would be highly appretiated. Thank you for your work! D.

**Comment by Dukenware** [comment] 2024-02-20 20:49
Just a note, after removing the include project lines from WebUi.csproj and deleting all test project, I am able to build the solution, however I think that's not the optimal way to do things.

**Comment by ubhaya** [comment] 2024-02-24 08:34
duplicate of #36.

I have fixed this in the main branch. still pending a release. I am trying to release this with the Maui project. I am busy with my day job. I will reengage with the project at the end of March. I would be more pleased if someone could help with the MAUI project.

**Closed by ubhaya** 2024-02-24 08:34 UTC
Labels: duplicate

**Comment by ubhaya** [comment] 2024-02-24 09:00
I double-confirmed the issue. There is no issue in ApiClient.g.cs. It generates automatically every time the project builds in debug configuration. props and target files are the culprits. I used these for generating the MudBlazor project using the Bootstrap project. No need to delete the test project.
